# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:     
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: build mkdocs
          command: mkdocs build

workflows:
  sample: 
    jobs:
      - build-and-test